# Generated by Django 4.0.3 on 2025-05-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_items',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
