# Generated by Django 5.2.1 on 2025-05-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0004_alter_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
