# Generated by Django 5.2.1 on 2025-06-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0006_category_remove_order_item_remove_order_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='online_food_delivery_platform\x0coodOrder\\Images'),
        ),
    ]
