# Generated by Django 5.2.1 on 2025-06-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0009_alter_ingredient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
