# Generated by Django 5.2.1 on 2025-06-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0010_remove_fooditem_ingredients_delete_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='food_comment',
            field=models.TextField(blank=True, help_text='Review specifically about the food', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='food_rating',
            field=models.PositiveIntegerField(blank=True, help_text='Rating for the food (1-5)', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(help_text='Overall review of the restaurant'),
        ),
    ]
